-- Pickty V2 초기 스키마 (신규 환경 전용 — 데이터 이관 없음)
-- PostgreSQL

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    email varchar(255) NULL,
    nickname varchar(255) NOT NULL,
    profile_image_url varchar(255) NULL,
    display_avatar_url varchar(255) NULL,
    user_name varchar(255) NULL,
    account_status varchar(32) NOT NULL DEFAULT 'ACTIVE',
    birth_year integer NULL,
    gender varchar(16) NULL,
    onboarding_completed_at timestamp(6) NULL,
    role varchar(255) NOT NULL,
    merged_into_user_id bigint NULL,
    CONSTRAINT users_account_status_check
        CHECK (account_status IN ('PENDING', 'ACTIVE', 'DELETED', 'MERGED')),
    CONSTRAINT users_gender_check
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT users_role_check
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_merged_into FOREIGN KEY (merged_into_user_id) REFERENCES users (id)
);

CREATE TABLE tier_templates (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    title varchar(100) NOT NULL,
    description text NULL,
    items jsonb NOT NULL,
    version integer NOT NULL,
    parent_template_id uuid NULL,
    creator_id bigint NULL,
    board_config jsonb NULL,
    thumbnail_url varchar(2048) NULL,
    template_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    like_count bigint NOT NULL DEFAULT 0,
    comment_count bigint NOT NULL DEFAULT 0,
    view_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT tier_templates_status_check
        CHECK (template_status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT fk_tier_templates_parent FOREIGN KEY (parent_template_id) REFERENCES tier_templates (id)
);

CREATE INDEX ix_tier_templates_creator ON tier_templates (creator_id);
CREATE INDEX ix_tier_templates_status_created ON tier_templates (template_status, created_at DESC);

CREATE TABLE tier_results (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    template_id uuid NOT NULL,
    user_id bigint NULL,
    snapshot_data jsonb NOT NULL,
    is_public boolean NOT NULL,
    is_temporary boolean NOT NULL,
    result_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    list_title varchar(100) NULL,
    list_description text NULL,
    thumbnail_url text NULL,
    up_count bigint NOT NULL DEFAULT 0,
    down_count bigint NOT NULL DEFAULT 0,
    comment_count bigint NOT NULL DEFAULT 0,
    view_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT tier_results_result_status_check
        CHECK (result_status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT fk_tier_results_template FOREIGN KEY (template_id) REFERENCES tier_templates (id)
);

CREATE INDEX ix_tier_results_template ON tier_results (template_id);
CREATE INDEX ix_tier_results_user ON tier_results (user_id);

CREATE TABLE worldcup_templates (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    title varchar(100) NOT NULL,
    description text NULL,
    items jsonb NOT NULL,
    layout_mode varchar(32) NOT NULL DEFAULT 'split_diagonal',
    version integer NOT NULL,
    creator_id bigint NULL,
    thumbnail_url varchar(2048) NULL,
    template_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    like_count bigint NOT NULL DEFAULT 0,
    comment_count bigint NOT NULL DEFAULT 0,
    view_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT worldcup_templates_template_status_check
        CHECK (template_status IN ('ACTIVE', 'DELETED'))
);

CREATE INDEX ix_worldcup_templates_creator ON worldcup_templates (creator_id);
CREATE INDEX ix_worldcup_templates_status_created ON worldcup_templates (template_status, created_at DESC);

CREATE TABLE worldcup_item_stats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    template_id uuid NOT NULL,
    item_id bigint NOT NULL,
    match_count bigint NOT NULL DEFAULT 0,
    win_count bigint NOT NULL DEFAULT 0,
    rerolled_count bigint NOT NULL DEFAULT 0,
    dropped_count bigint NOT NULL DEFAULT 0,
    kept_both_count bigint NOT NULL DEFAULT 0,
    final_win_count bigint NOT NULL DEFAULT 0,
    reached_16_count bigint NOT NULL DEFAULT 0,
    reached_8_count bigint NOT NULL DEFAULT 0,
    reached_4_count bigint NOT NULL DEFAULT 0,
    reached_final_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT uq_worldcup_item_stats_tpl_item UNIQUE (template_id, item_id),
    CONSTRAINT fk_worldcup_item_stats_template FOREIGN KEY (template_id) REFERENCES worldcup_templates (id)
);

CREATE INDEX ix_worldcup_item_stats_template ON worldcup_item_stats (template_id);

CREATE TABLE social_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    user_id bigint NOT NULL,
    provider varchar(255) NOT NULL,
    provider_id varchar(255) NOT NULL,
    provider_attributes jsonb NULL,
    CONSTRAINT social_accounts_provider_check
        CHECK (provider IN (
            'GOOGLE', 'NAVER', 'KAKAO', 'CHZZK', 'SOOP', 'TWITCH', 'DISCORD', 'X', 'APPLE'
        )),
    CONSTRAINT uk_social_accounts_provider_user UNIQUE (provider, provider_id),
    CONSTRAINT fk_social_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE reactions (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    target_type varchar(32) NOT NULL,
    target_id uuid NOT NULL,
    reaction_type varchar(16) NOT NULL,
    user_id bigint NULL,
    guest_ip_hash varchar(64) NULL,
    CONSTRAINT reactions_reaction_type_check
        CHECK (reaction_type IN ('LIKE', 'UPVOTE', 'DOWNVOTE')),
    CONSTRAINT reactions_target_type_check
        CHECK (target_type IN (
            'TIER_TEMPLATE', 'TIER_RESULT', 'WORLDCUP_TEMPLATE', 'WORLDCUP_RESULT',
            'COMMUNITY_POST'
        ))
);

CREATE INDEX ix_reactions_target ON reactions (target_type, target_id);

-- 회원: 타겟당 반응 1행 — API 연타·레이스 시 DB가 중복 차단
CREATE UNIQUE INDEX uk_reactions_member_target
    ON reactions (target_type, target_id, user_id)
    WHERE user_id IS NOT NULL;

-- 비회원: IP 해시당 반응 1행 (user_id IS NULL 행만)
CREATE UNIQUE INDEX uk_reactions_guest_target
    ON reactions (target_type, target_id, guest_ip_hash)
    WHERE user_id IS NULL AND guest_ip_hash IS NOT NULL;

CREATE TABLE comments (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    target_type varchar(32) NOT NULL,
    target_id uuid NOT NULL,
    user_id bigint NULL,
    parent_comment_id uuid NULL,
    body text NOT NULL,
    comment_status varchar(16) NOT NULL,
    author_name varchar(64) NULL,
    author_ip_prefix varchar(45) NULL,
    guest_password varchar(255) NULL,
    guest_ip_hash varchar(64) NULL,
    CONSTRAINT comments_comment_status_check
        CHECK (comment_status IN ('ACTIVE', 'DELETED')),
    CONSTRAINT comments_target_type_check
        CHECK (target_type IN (
            'TIER_TEMPLATE', 'TIER_RESULT', 'WORLDCUP_TEMPLATE', 'WORLDCUP_RESULT',
            'COMMUNITY_POST'
        )),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES comments (id)
);

CREATE INDEX ix_comments_target ON comments (target_type, target_id);
CREATE INDEX ix_comments_parent ON comments (parent_comment_id);

CREATE TABLE community_posts (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    title varchar(200) NOT NULL,
    content_html text NOT NULL,
    author_id bigint NULL,
    guest_nickname varchar(64) NULL,
    guest_password_hash varchar(255) NULL,
    guest_ip_hash varchar(64) NULL,
    guest_ip_prefix varchar(45) NULL,
    view_count bigint NOT NULL DEFAULT 0,
    comment_count bigint NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_community_posts_author_or_guest
        CHECK (
            (author_id IS NOT NULL AND guest_nickname IS NULL AND guest_password_hash IS NULL AND guest_ip_hash IS NULL)
            OR
            (author_id IS NULL AND guest_nickname IS NOT NULL AND guest_password_hash IS NOT NULL
             AND guest_ip_hash IS NOT NULL AND guest_ip_prefix IS NOT NULL)
        ),
    CONSTRAINT community_posts_status_check CHECK (status IN ('ACTIVE', 'DELETED'))
);

CREATE INDEX ix_community_posts_status_created_at ON community_posts (status, created_at DESC);
CREATE INDEX ix_community_posts_author_id ON community_posts (author_id);
